server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    max-http-form-post-size: 10485760

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://highre.ce6gljpu8bbr.ap-northeast-2.rds.amazonaws.com/temp?serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: green123
  redis:
    host: localhost
    port: 6379
  sql:
    init:
      schema-locations:
        - classpath:db/table.sql
      data-locations:
        - classpath:db/data.sql
  # h2:
  #   console:
  #     enabled: true
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
